language: php

php:
    - 7.2
    - 7.3snapshot

install:
    - composer update

script:
    # run tests for tested posts (with "tested: true" in header configuration)
    - vendor/bin/phpunit --coverage-clover coverage.xml

    # static analysis
    - composer check-cs
    - composer phpstan

    # test that website is generated
    - vendor/bin/statie generate source

after_script:
    # upload coverage.xml file to Coveralls to analyze it
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
    - php coveralls.phar --verbose;

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

after_deploy:
    # tweets posts
    - |
      if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
        packages/StatieTweetPublisher/bin/publish-new-tweet
      fi

notifications:
    email:
        on_success: newer
        on_failure: always
